nines_feedback:
    default_status: submitted
    public_status: published
    subject: New feedback received
    sender: noreply@example.com
    recipients:
        - user@example.com
        - another@example.com
    routing:
        nines_blog:
            class: Nines\BlogBundle\Entity\Page
            route: nines_blog_page_show
        work:
            class: App\Entity\Work
            route: work_show
        person:
            class: App\Entity\Person
            route: person_show
        blog_post:
            class: Nines\BlogBundle\Entity\Post
            route: post_show
        blog_page:
            class: Nines\BlogBundle\Entity\Page
            route: page_show
