twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - 'bootstrap_3_horizontal_layout.html.twig'
        - "@NinesUtil/form/fields.html.twig"
        - '@TetranzSelect2Entity/Form/fields.html.twig'
        - 'jquery.collection.html.twig'
    globals:
        comment_service: '@Nines\FeedbackBundle\Services\CommentService'
        text_service: '@Nines\UtilBundle\Services\Text'
        piwik_enabled: '%dhil.piwik_enabled%'
        piwik_url: '%dhil.piwik_url%'
        piwik_siteid: '%dhil.piwik_siteid%'
        piwik_domain: '%dhil.piwik_domain%'
    date:
        format: d.m.Y, H:i:s
        interval_format: '%%d days'
