imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "../../vendor/beberlei/DoctrineExtensions/config/mysql.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:
        enabled: true
        logging: false
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/3.4/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        name: PHP_SESSION_NEWN
        cookie_path: '%router.request_context.base_url%'
        cookie_domain: '%router.request_context.host%'
        cookie_secure: '%secure_cookies%'
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    form_themes:
        - 'bootstrap_3_horizontal_layout.html.twig'
        - 'NinesUtilBundle:form:fields.html.twig'
        - 'TetranzSelect2EntityBundle:Form:fields.html.twig'
        - '::jquery.collection.html.twig'
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        '%kernel.project_dir%/vendor/ubermichael/nines/UtilBundle/Resources/views': NinesUtilBundle
        '%kernel.project_dir%/vendor/ubermichael/nines/UserBundle/Resources/views': NinesUser
    globals:
        comment_service: '@Nines\FeedbackBundle\Services\CommentService'
        text_service: '@Nines\UtilBundle\Services\Text'
        piwik_enabled: '%dhil.piwik_enabled%'
        piwik_url: '%dhil.piwik_url%'
        piwik_siteid: '%dhil.piwik_siteid%'
        piwik_domain: '%dhil.piwik_domain%'
    date:
        format: d.m.Y, H:i:s
        interval_format: '%%d days'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
#        logging: false
#        profiling: false
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: dir       # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # bootstrapy pagination
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Nines\UserBundle\Entity\User
    profile:
        form:
            type: Nines\UserBundle\Form\ProfileType
    change_password:
        form:
            type: Nines\UserBundle\Form\PasswordType
    from_email:
        address:        noreply@dhil.lib.sfu.ca
        sender_name:    Do Not Reply

fos_ck_editor:
    input_sync: true
    default_config: newn_config
    configs:
        newn_config:
            entities: false
            toolbar:
                - [ Source, -, Cut, Copy, Paste, PasteText, PasteFromWord, -, Undo, Redo ]
                - [ Link, Unlink, Anchor, -, SpecialChar ]
                - [ Format, Styles, -, Bold, Italic, Strike, -, RemoveFormat, -, NumberedList, BulletedList, -, Indent, Outdent, -, Blockquote, -, JustifyLeft, JustifyCenter, JustifyRight, JustifyBlock ]

knp_menu:
    twig:
        template: KnpMenuBundle::menu.html.twig

nines_feedback:
    default_status: submitted
    public_status: published
    commenting:
        work:
            class: AppBundle\Entity\Work
            route: work_show
        person:
            class: AppBundle\Entity\Person
            route: person_show
        blog_post:
            class: Nines\BlogBundle\Entity\Post
            route: post_show
        blog_page:
            class: Nines\BlogBundle\Entity\Page
            route: page_show

nines_blog:
    default_status: draft
    default_category: none

nines_user:
    permission_levels: [ ROLE_ADMIN, ROLE_BLOG_ADMIN, ROLE_COMMENT_ADMIN, ROLE_CONTENT_ADMIN, ROLE_CONTENT_EDITOR, ROLE_DC_EDITOR ]
